name: tinode
description: >
  This SDK implements Tinode client-side protocol for multi-platform 
  applications based on Dart. Supports Flutter mobile, Flutter desktop, 
  and pure Dart CLI/server applications.
version: 2.0.0
homepage: https://github.com/scalecode-solutions/dart-sdk
repository: https://github.com/scalecode-solutions/dart-sdk
issue_tracker: https://github.com/scalecode-solutions/dart-sdk/issues

environment:
  sdk: ^3.0.0

dependencies:
  rxdart: ^0.28.0
  web_socket_channel: ^3.0.1
  get_it: ^8.0.2
  http: ^1.2.2
  http_parser: ^4.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
  mockito: ^5.4.4
  build_runner: ^2.4.13
